class_name GraphicsPack
extends Resource

## THE GRAPHICS CONTRACT (beta 0.3.1).
##
## One resource owning every semantic visual the game can ask for. Screens
## request fields on this; no screen anywhere holds an asset path.
##
## ## Why the fields ARE the contract
##
## Completeness is the property that matters at a gate — §7.5 requires that no
## renderer conversion ever silently falls back because the pack was short an
## asset. Expressing each asset as a typed exported field makes "missing" mean
## `null`, which `validate()` can walk mechanically. A Dictionary keyed by
## string would have moved that check to runtime and made a typo indetectable
## until the screen holding it was opened on a device.
##
## Swapping the entire look is one `.tres` path. That is the plumbing the
## graphics jig is meant to reuse (authorization §19), which is why it is built
## release-shaped now rather than as scaffolding to be replaced later.
##
## Generated by `tools/gen_pack_resource.gd` from the pack manifest — a hand-
## maintained list of forty-four resource paths would drift the first time an
## asset was renamed.

@export_group("Screen chrome")
@export var screen_bg: Texture2D
@export var panel: Texture2D
@export var button_normal: Texture2D
@export var button_pressed: Texture2D
@export var button_selected: Texture2D
@export var button_disabled: Texture2D
@export var rule: Texture2D
@export var scroll_track: Texture2D
@export var scroll_thumb: Texture2D
@export var bar_track: Texture2D
@export var bar_fill_link: Texture2D
@export var bar_fill_ice: Texture2D
@export var bar_fill_charge: Texture2D
@export var bar_fill_charge_ready: Texture2D
## The start screen's wordmark (beta 0.3.2 §12). Art, not text — nothing loads a
## font to draw it.
@export var title_logo: Texture2D

@export_group("Battle chrome")
@export var avatar_box: Texture2D
@export var program_box_idle: Texture2D
@export var program_box_charged: Texture2D
@export var program_box_ready: Texture2D
@export var program_box_armed: Texture2D
@export var board_surround: Texture2D
@export var packet_cell: Texture2D
@export var build_slot: Texture2D

@export_group("Packet")
## Keyed by `Types.PacketShape`. Order is gameplay identity, not presentation.
@export var packet_glyph: Array[Texture2D] = []
@export var ring_selected: Texture2D
@export var ring_targeting: Texture2D

@export_group("Overlay")
@export var badge_player: Texture2D
@export var badge_enemy: Texture2D
## Keyed by `Tile.Special.Type`. The badge's centre mark, and since D-037 the
## whole type signal.
@export var overlay_mark: Array[Texture2D] = []
## Keyed by `Tile.Special.Type`. **Retained but not displayed** — the type ring
## is suspended (D-037) pending a designer decision. Kept in the contract so
## restoring it needs no schema change.
@export var overlay_ring: Array[Texture2D] = []
## Countdown numerals 0-9, indexed by digit (beta 0.3.2 §11). An armed overlay's
## remaining turns are composed from these, so the board depends on no typeface.
@export var countdown_digit: Array[Texture2D] = []

@export_group("Icons")
@export var icon_menu: Texture2D
@export var icon_arrow_up: Texture2D
@export var icon_arrow_down: Texture2D
@export var icon_cancel: Texture2D

@export_group("Palette")
## `res://` path to the palette SVG, read as text at startup. See
## `PacketPalette` for why it is parsed rather than compiled in.
@export var palette_svg: String = ""


## Which array fields must be full, and how full.
##
## Sized from the ENUMS rather than from literals, so adding a Packet shape or a
## special type makes the pack fail validation instead of quietly rendering the
## new one as MISSING.
func _expected_sizes() -> Dictionary:
	return {
		"packet_glyph": Types.PacketShape.size(),
		"overlay_mark": Tile.Special.Type.size(),
		"overlay_ring": Tile.Special.Type.size(),
		"countdown_digit": 10,
	}


## Every semantic key this pack fails to supply.
##
## Walks the exported properties rather than a maintained list: a field added
## above is validated from the moment it exists, with nothing else to remember.
## Empty return means the pack is complete.
func validate() -> PackedStringArray:
	var missing := PackedStringArray()
	var sizes := _expected_sizes()

	for prop in get_property_list():
		if not (int(prop["usage"]) & PROPERTY_USAGE_SCRIPT_VARIABLE):
			continue
		var key := str(prop["name"])
		var value = get(key)

		match int(prop["type"]):
			TYPE_OBJECT:
				if value == null:
					missing.append(key)
			TYPE_ARRAY:
				var want := int(sizes.get(key, 0))
				var arr: Array = value if value != null else []
				if arr.size() != want:
					missing.append("%s (has %d, needs %d)" % [key, arr.size(), want])
					continue
				for i in arr.size():
					if arr[i] == null:
						missing.append("%s[%d]" % [key, i])
			TYPE_STRING:
				if str(value).strip_edges().is_empty():
					missing.append(key)

	return missing
