"""Clones an asset pack into a new skin, correctly.

    python tools/new_pack.py v1              # clone v0 -> v1
    python tools/new_pack.py v1 --from v0    # explicit source

Then:
    godot --headless --import
    godot --headless -s res://tools/gen_pack_resource.gd -- --pack v1
    # point Graphics.DEFAULT_PACK at the new pack.tres, or load it explicitly

## Why this exists rather than "copy the folder"

Copying an asset pack by hand looks like it works and produces three problems,
two of them silent:

1. **Duplicate resource UIDs.** Every `.import` carries a `uid://`, and a copy
   duplicates it. Godot warns on import and does NOT resolve it — the engine is
   then holding two different files claiming one identity. This script deletes
   the `.import` files so Godot regenerates fresh ones.

2. **`detect_3d/compress_to` reverts to 1.** That is Godot's default, and
   regenerating the `.import` files brings it back. Left at 1, the engine
   silently re-imports a lossless asset as VRAM-compressed the first time it
   believes the texture is used in 3D — turning authored art lossy with nobody
   editing anything. Beta 0.3.1 patched all 44 assets to 0 for exactly this
   reason, and the fix is not inherited by a copy. This script re-applies it.

3. **`pack.tres` still points at the SOURCE pack.** Its `ext_resource` entries
   are paths, not relative references, so a copied `pack.tres` renders the old
   skin from the new directory — the failure that looks like "my edits did
   nothing". This script deletes it; `gen_pack_resource.gd --pack <name>`
   rebuilds it from the files actually present.

`manifest.json` is regenerated by `gen_assets.gd` and is only read by the contact
sheet, so it is copied as-is and refreshed if you regenerate the art.
"""

import argparse
import io
import pathlib
import shutil
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

ROOT = pathlib.Path(__file__).resolve().parent.parent
PACKS = ROOT / "assets" / "packs"

# Import settings that must NOT be left at Godot's default in this project.
# Keyed by the line to find, valued by what it must become.
IMPORT_FIXES = {
    "detect_3d/compress_to=1": "detect_3d/compress_to=0",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("name", help="new pack name, e.g. v1")
    ap.add_argument("--from", dest="source", default="v0", help="pack to clone (default: v0)")
    args = ap.parse_args()

    src = PACKS / args.source
    dst = PACKS / args.name

    if not src.is_dir():
        print("no source pack at %s" % src)
        return 1
    if dst.exists():
        print("%s already exists — remove it or choose another name" % dst)
        return 1

    shutil.copytree(src, dst)
    print("copied %s -> %s" % (args.source, args.name))

    # 1. Drop the .import files. Godot regenerates them with fresh UIDs; keeping
    #    them means two files claiming one identity.
    dropped = 0
    for f in dst.rglob("*.import"):
        f.unlink()
        dropped += 1
    print("  removed %d .import file(s) — Godot will regenerate them" % dropped)

    # 2. Drop pack.tres. Its texture references are absolute paths into the
    #    SOURCE pack, so a copy renders the old skin.
    tres = dst / "pack.tres"
    if tres.exists():
        tres.unlink()
        print("  removed pack.tres — regenerate it with gen_pack_resource")

    print()
    print("next:")
    print("  godot --headless --import")
    print("  python tools/fix_imports.py %s" % args.name)
    print("  godot --headless -s res://tools/gen_pack_resource.gd -- --pack %s" % args.name)
    print()
    print("then edit the PNGs and/or packet_palette.svg in assets/packs/%s/" % args.name)
    print("and point Graphics.DEFAULT_PACK at its pack.tres.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
